filter:
    excluded_paths:
        - tests/*
checks:
    php: true
coding_style:
  php:
      indentation:
          general:
              size: 1
build: true
    environment:
        php:
            version: 5.6